version: "3.3"
services:
  web: 
    build: .
    command: npm run start
    image: josu3e/orbis-training-docker:2.0.0
    volumes:
      - .:/app
    ports:
      - "3030:1042"
      - "35729:35729"

  test:
    build: .
    image: node:10.10.0-slim
    links: 
      - web
    command: curl web:1042

